core:
  redis:
    nonpersistent:
      host: localhost
      port: 6379
    persistent:
      host: localhost
      port: 6379

datastore:
  hosts: ["localhost:9200"]

filestore:
  cache: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@localhost:9000?s3_bucket=al-cache&use_ssl=False"]
  storage: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@localhost:9000?s3_bucket=al-storage&use_ssl=False"]

logging:
  log_as_json: false
  log_to_console: true
  log_to_file: false
  log_to_syslog: false